language: scala
scala:
    - "2.11.3"
jdk:
    - openjdk7
sbt_args: -no-colors


after_success:
    - echo ttt > test.txt
    - chmod 0400 /home/travis/build/bkowalik/zpi-komunikator/zpi-server.pem
    - scp -o "StrictHostKeyChecking no" -i /home/travis/build/bkowalik/zpi-komunikator/zpi-server.pem test.txt ubuntu@ec2-54-77-232-158.eu-west-1.compute.amazonaws.com:test.txt 