language: scala
scala:
    - "2.11.3"
jdk:
    - openjdk7
sbt_args: -no-colors

after_success:
    - sbt dist
    - chmod 0400 /home/travis/build/bkowalik/zpi-komunikator/zpi-server.pem
    - scp -o "StrictHostKeyChecking no" -i /home/travis/build/bkowalik/zpi-komunikator/zpi-server.pem /home/travis/build/bkowalik/zpi-komunikator/target/universal/zpi-server-0.1.zip ubuntu@ec2-54-77-232-158.eu-west-1.compute.amazonaws.com:zpi-server-0.1.zip 
    - ssh -i /home/travis/build/bkowalik/zpi-komunikator/zpi-server.pem ubuntu@ec2-54-77-232-158.eu-west-1.compute.amazonaws.com screen -d -m ./run.sh